import { utilsData } from '../interfaces'

export const Data: utilsData[] = [
  {
    number: 1,
    id: '1429',
    type: 'serie',
    genre: 'animation',
    name: 'Attack on Titan',
  },
  {
    number: 2,
    id: '533514',
    type: 'movie',
    genre: 'animation',
    name: 'Violet Evergarden: The Movie',
  },
  {
    number: 3,
    id: '75214',
    type: 'serie',
    genre: 'animation',
    name: 'Violet Evergarden',
  },
  {
    number: 4,
    id: '63926',
    type: 'serie',
    genre: 'animation',
    name: 'One Punch Man',
  },
  {
    number: 5,
    id: '90937',
    type: 'serie',
    genre: 'animation',
    name: 'Beastars',
  },
  {
    number: 6,
    id: '45790',
    type: 'serie',
    genre: 'animation',
    name: "JoJo's Bizarre Adventure",
  },
  {
    number: 7,
    id: '112160',
    type: 'serie',
    genre: 'animation',
    name: 'The Way of the Househusband',
  },
  {
    number: 8,
    id: '61459',
    type: 'serie',
    genre: 'animation',
    name: 'Parasyte: The Maxim',
  },
  {
    number: 9,
    id: '33880',
    type: 'serie',
    genre: 'animation',
    name: 'The Legend of Korra',
  },
  {
    number: 10,
    id: '246',
    type: 'serie',
    genre: 'animation',
    name: 'Avatar: The Last Airbender',
  },
  {
    number: 11,
    id: '71024',
    type: 'serie',
    genre: 'animation',
    name: 'Castlevania',
  },
  {
    number: 12,
    id: '85937',
    type: 'serie',
    genre: 'animation',
    name: 'Demon Slayer: Kimetsu no Yaiba',
  },
  {
    number: 13,
    id: '30991',
    type: 'serie',
    genre: 'animation',
    name: 'Cowboy Bebop',
  },
  {
    number: 14,
    id: '13916',
    type: 'serie',
    genre: 'animation',
    name: 'Death Note',
  },
  {
    number: 15,
    id: '79166',
    type: 'serie',
    genre: 'animation',
    name: 'Grand Blue',
  },
  {
    number: 16,
    id: '61663',
    type: 'serie',
    genre: 'animation',
    name: 'Your Lie in April',
  },
  {
    number: 17,
    id: '67389',
    type: 'serie',
    genre: 'animation',
    name: 'Golden Time',
  },
  {
    number: 18,
    id: '95557',
    type: 'serie',
    genre: 'animation',
    name: 'Invincible',
  },
  {
    number: 19,
    id: '46260',
    type: 'serie',
    genre: 'animation',
    name: 'Naruto',
  },
  {
    number: 20,
    id: '83100',
    type: 'serie',
    genre: 'animation',
    name: 'Dororo',
  },
  { number: 21, id: '1668', type: 'serie', genre: 'la', name: 'Friends' },
  {
    number: 22,
    id: '1100',
    type: 'serie',
    genre: 'la',
    name: 'How I Met Your Mother',
  },
  {
    number: 23,
    id: '1399',
    type: 'serie',
    genre: 'la',
    name: 'Game of Thrones',
  },
  {
    number: 24,
    id: '94605',
    type: 'serie',
    genre: 'animation',
    name: 'Arcane',
  },
  { number: 25, id: '85552', type: 'serie', genre: 'la', name: 'Euphoria' },
  {
    number: 26,
    id: '81356',
    type: 'serie',
    genre: 'la',
    name: 'Sex Education',
  },
  {
    number: 27,
    id: '66732',
    type: 'serie',
    genre: 'la',
    name: 'Stranger Things',
  },
  { number: 28, id: '84958', type: 'serie', genre: 'la', name: 'Loki' },
  {
    number: 29,
    id: '572154',
    type: 'serie',
    genre: 'animation',
    name: 'Rascal Does Not Dream of Bunny Girl Senpai',
  },
  { number: 30, id: '504949', type: 'movie', genre: 'la', name: 'The King' },
  {
    number: 31,
    id: '634649',
    type: 'movie',
    genre: 'la',
    name: 'Spider-Man: No Way Home',
  },
  {
    number: 32,
    id: '429617',
    type: 'movie',
    genre: 'la',
    name: 'Spider-Man: Far from Home',
  },
  {
    number: 33,
    id: '315635',
    type: 'movie',
    genre: 'la',
    name: 'Spider-Man: Homecoming',
  },
  {
    number: 34,
    id: '324857',
    type: 'movie',
    genre: 'animation',
    name: 'Spider-Man: Into the Spider-Verse',
  },
  {
    number: 35,
    id: '568124',
    type: 'movie',
    genre: 'animation',
    name: 'Encanto',
  },
  { number: 36, id: '337404', type: 'movie', genre: 'la', name: 'Cruella' },
  {
    number: 37,
    id: '354912',
    type: 'movie',
    genre: 'animation',
    name: 'Coco',
  },
  {
    number: 38,
    id: '447332',
    type: 'movie',
    genre: 'la',
    name: 'A Quiet Place',
  },
  { number: 39, id: '438631', type: 'movie', genre: 'la', name: 'Dune' },
  {
    number: 40,
    id: '82816',
    type: 'serie',
    genre: 'la',
    name: 'Lovecraft Country',
  },
  {
    number: 41,
    id: '499932',
    type: 'movie',
    genre: 'la',
    name: 'The Devil All the Time',
  },
  { number: 42, id: '312221', type: 'movie', genre: 'la', name: 'Creed' },
  { number: 43, id: '635731', type: 'movie', genre: 'la', name: 'Pig' },
  {
    number: 44,
    id: '299534',
    type: 'movie',
    genre: 'la',
    name: 'Avengers: Endgame',
  },
  {
    number: 45,
    id: '299536',
    type: 'movie',
    genre: 'la',
    name: 'Avengers: Infinity War',
  },
  { number: 46, id: '244786', type: 'movie', genre: 'la', name: 'Whiplash' },
  {
    number: 47,
    id: '502033',
    type: 'movie',
    genre: 'la',
    name: 'Sound of Metal',
  },
  {
    number: 48,
    id: '76203',
    type: 'movie',
    genre: 'la',
    name: '12 Years a Slave',
  },
  { number: 49, id: '475557', type: 'movie', genre: 'la', name: 'Joker' },
  {
    number: 50,
    id: '4613',
    type: 'serie',
    genre: 'la',
    name: 'Band of Brothers',
  },
]
