import { utilsData } from '../interfaces';

export const Data: utilsData[] = [
  {
    number: 1,
    id: 'tt2560140',
    type: 'serie',
    genre: 'animation',
    name: 'Attack on Titan',
  },
  {
    number: 2,
    id: 'tt8652818',
    type: 'movie',
    genre: 'animation',
    name: 'Violet Evergarden: The Movie',
  },
  {
    number: 3,
    id: 'tt7078180',
    type: 'serie',
    genre: 'animation',
    name: 'Violet Evergarden',
  },
  {
    number: 4,
    id: 'tt4508902',
    type: 'serie',
    genre: 'animation',
    name: 'One Punch Man',
  },
  {
    number: 5,
    id: 'tt11043632',
    type: 'serie',
    genre: 'animation',
    name: 'Beastars',
  },
  {
    number: 6,
    id: 'tt2359704',
    type: 'serie',
    genre: 'animation',
    name: "JoJo's Bizarre Adventure",
  },
  {
    number: 7,
    id: 'tt13357124',
    type: 'serie',
    genre: 'animation',
    name: 'The Way of the Househusband',
  },
  {
    number: 8,
    id: 'tt3358020',
    type: 'serie',
    genre: 'animation',
    name: 'Parasyte: The Maxim',
  },
  {
    number: 9,
    id: 'tt1695360',
    type: 'serie',
    genre: 'animation',
    name: 'The Legend of Korra',
  },
  {
    number: 10,
    id: 'tt0417299',
    type: 'serie',
    genre: 'animation',
    name: 'Avatar: The Last Airbender',
  },
  {
    number: 11,
    id: 'tt6517102',
    type: 'serie',
    genre: 'animation',
    name: 'Castlevania',
  },
  {
    number: 12,
    id: 'tt9335498',
    type: 'serie',
    genre: 'animation',
    name: 'Demon Slayer: Kimetsu no Yaiba',
  },
  {
    number: 13,
    id: 'tt0213338',
    type: 'serie',
    genre: 'animation',
    name: 'Cowboy Bebop',
  },
  {
    number: 14,
    id: 'tt0877057',
    type: 'serie',
    genre: 'animation',
    name: 'Death Note',
  },
  {
    number: 15,
    id: 'tt8086718',
    type: 'serie',
    genre: 'animation',
    name: 'Grand Blue',
  },
  {
    number: 16,
    id: 'tt3895150',
    type: 'serie',
    genre: 'animation',
    name: 'Your Lie in April',
  },
  {
    number: 17,
    id: 'tt3105452',
    type: 'serie',
    genre: 'animation',
    name: 'Golden Time',
  },
  {
    number: 18,
    id: 'tt6741278',
    type: 'serie',
    genre: 'animation',
    name: 'Invincible',
  },
  {
    number: 19,
    id: 'tt0409591',
    type: 'serie',
    genre: 'animation',
    name: 'Naruto',
  },
  {
    number: 20,
    id: 'tt9458304',
    type: 'serie',
    genre: 'animation',
    name: 'Dororo',
  },
  { number: 21, id: 'tt0108778', type: 'serie', genre: 'la', name: 'Friends' },
  {
    number: 22,
    id: 'tt0460649',
    type: 'serie',
    genre: 'la',
    name: 'How I Met Your Mother',
  },
  {
    number: 23,
    id: 'tt0944947',
    type: 'serie',
    genre: 'la',
    name: 'Game of Thrones',
  },
  {
    number: 24,
    id: 'tt11126994',
    type: 'serie',
    genre: 'animation',
    name: 'Arcane',
  },
  { number: 25, id: 'tt8772296', type: 'serie', genre: 'la', name: 'Euphoria' },
  {
    number: 26,
    id: 'tt7767422',
    type: 'serie',
    genre: 'la',
    name: 'Sex Education',
  },
  {
    number: 27,
    id: 'tt4574334',
    type: 'serie',
    genre: 'la',
    name: 'Stranger Things',
  },
  { number: 28, id: 'tt9140554', type: 'serie', genre: 'la', name: 'Loki' },
  {
    number: 29,
    id: 'tt8993398',
    type: 'serie',
    genre: 'animation',
    name: 'Rascal Does Not Dream of Bunny Girl Senpai',
  },
  { number: 30, id: 'tt7984766', type: 'movie', genre: 'la', name: 'The King' },
  {
    number: 31,
    id: 'tt10872600',
    type: 'movie',
    genre: 'la',
    name: 'Spider-Man: No Way Home',
  },
  {
    number: 32,
    id: 'tt6320628',
    type: 'movie',
    genre: 'la',
    name: 'Spider-Man: Far from Home',
  },
  {
    number: 33,
    id: 'tt2250912',
    type: 'movie',
    genre: 'la',
    name: 'Spider-Man: Homecoming',
  },
  {
    number: 34,
    id: 'tt4633694',
    type: 'movie',
    genre: 'animation',
    name: 'Spider-Man: Into the Spider-Verse',
  },
  {
    number: 35,
    id: 'tt2953050',
    type: 'movie',
    genre: 'animation',
    name: 'Encanto',
  },
  { number: 36, id: 'tt3228774', type: 'movie', genre: 'la', name: 'Cruella' },
  {
    number: 37,
    id: 'tt2380307',
    type: 'movie',
    genre: 'animation',
    name: 'Coco',
  },
  {
    number: 38,
    id: 'tt6644200',
    type: 'movie',
    genre: 'la',
    name: 'A Quiet Place',
  },
  { number: 39, id: 'tt1160419', type: 'movie', genre: 'la', name: 'Dune' },
  {
    number: 40,
    id: 'tt6905686',
    type: 'serie',
    genre: 'la',
    name: 'Lovecraft Country',
  },
  {
    number: 41,
    id: 'tt7395114',
    type: 'movie',
    genre: 'la',
    name: 'The Devil All the Time',
  },
  { number: 42, id: 'tt3076658', type: 'movie', genre: 'la', name: 'Creed' },
  { number: 43, id: 'tt11003218', type: 'movie', genre: 'la', name: 'Pig' },
  {
    number: 44,
    id: 'tt4154796',
    type: 'movie',
    genre: 'la',
    name: 'Avengers: Endgame',
  },
  {
    number: 45,
    id: 'tt4154756',
    type: 'movie',
    genre: 'la',
    name: 'Avengers: Infinity War',
  },
  { number: 46, id: 'tt2582802', type: 'movie', genre: 'la', name: 'Whiplash' },
  {
    number: 47,
    id: 'tt5363618',
    type: 'movie',
    genre: 'la',
    name: 'Sound of Metal',
  },
  {
    number: 48,
    id: 'tt2024544',
    type: 'movie',
    genre: 'la',
    name: '12 Years a Slave',
  },
  { number: 49, id: 'tt7286456', type: 'movie', genre: 'la', name: 'Joker' },
  {
    number: 49,
    id: 'tt0185906',
    type: 'serie',
    genre: 'la',
    name: 'Band of Brothers',
  },
];
